# Object files for the pmm module
KERN_OBJFILES += obj/kern/pmm/MATIntro/test.o
KERN_OBJFILES += obj/kern/pmm/MATInit/MATInit.o
KERN_OBJFILES += obj/kern/pmm/MATInit/test.o
KERN_OBJFILES += obj/kern/pmm/MATOp/MATOp.o
KERN_OBJFILES += obj/kern/pmm/MContainer/MContainer.o
KERN_OBJFILES += obj/kern/pmm/pmm.o
